; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; https://docs.platformio.org/en/latest/boards/espressif32/dfrobot_firebeetle2_esp32e.html

[env:dfrobot_firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
upload_protocol = esptool
framework = arduino
lib_deps = 
	fastled/FastLED
	milesburton/DallasTemperature
	adafruit/Adafruit EPD
	adafruit/Adafruit BusIO
	Wire
	zinggjm/GxEPD2
	dfrobot/DFRobot_BMP3XX
	https://github.com/boarchuz/HULP.git
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_filters = colorize, time, esp32_exception_decoder
debug_tool = esp-prog
debug_init_break = tbreak setup
build_flags = -DPPK2_DEBUG
