#!/usr/bin/env python3
"""Resolve the active rig and write include/generated/rig_config.h.

A rig is one hardware configuration (board + panel + sensor + the flags that
follow), described by a tracked header in include/rigs/. This picks one and
emits a two-line selector the firmware includes.

The selector's path is fixed on purpose. Switching rigs then changes a file's
*content*, not the project's file list, so PlatformIO's project checksum is
undisturbed and only the dependent objects recompile — unlike varying
PLATFORMIO_BUILD_FLAGS, which deletes every env's build directory.

    gen_rig_config.py <rig>     # used by the idf.py path in src/CMakeLists.txt
"""

import os
import re
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RIGS_DIR = os.path.join(PROJECT_ROOT, "include", "rigs")
OUTPUT = os.path.join(PROJECT_ROOT, "include", "generated", "rig_config.h")


def available():
    """Rig names, in listing order. Leading underscore means not a rig."""
    if not os.path.isdir(RIGS_DIR):
        return []
    return sorted(f[:-2] for f in os.listdir(RIGS_DIR)
                  if f.endswith(".h") and not f.startswith("_"))


def rig_path(name):
    return os.path.join(RIGS_DIR, name + ".h")


def resolve(name):
    """Rig name -> header path, or exit with the list of valid names."""
    if name and not name.startswith("_") and os.path.isfile(rig_path(name)):
        return rig_path(name)
    what = f"Unknown rig {name!r}" if name else "No rig selected"
    sys.exit(f"{what}. Available: {', '.join(available()) or '(none)'}\n"
             f"Set custom_rig in platformio.ini, or pass RIG=<name> "
             f"(idf.py: -DRIG=<name>). See include/rigs/_template.h.")


def write(name):
    """Emit the selector for `name`. Leaves the file alone when unchanged, so
    its mtime marks real rig switches and nothing downstream rebuilds without
    cause. Returns the rig header's path."""
    path = resolve(name)
    # RIG_NAME is emitted here rather than written into each rig header: the
    # name is the filename, so deriving it is the only way it cannot disagree.
    #
    # The include path is relative to this file's own directory, not to
    # include/: a quoted include resolves against the includer first, and only
    # then against -I. The LP core sub-build reaches this file relatively too.
    text = ("// Auto-generated by scripts/gen_rig_config.py — do not edit\n"
            "#pragma once\n"
            f'#define RIG_NAME "{name}"\n'
            f'#include "../rigs/{name}.h"\n')
    if not (os.path.isfile(OUTPUT) and open(OUTPUT).read() == text):
        os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
        with open(OUTPUT, "w") as f:
            f.write(text)
    return path


def active_header():
    """Path of the rig header the generated selector currently points at, or
    None when nothing has been generated yet."""
    if not os.path.isfile(OUTPUT):
        return None
    m = re.search(r'^#include\s+"\.\./rigs/(.+)\.h"', open(OUTPUT).read(), re.MULTILINE)
    return rig_path(m.group(1)) if m else None


def check_template_lists_every_panel(displays):
    """The template is the menu humans read; DISPLAYS is what the font generator
    acts on. They are deliberately two copies, so make a divergence fail the
    build rather than leave an option nobody can discover.

    Only this direction needs checking: a panel in the menu that DISPLAYS does
    not know already breaks the build loudly, at displays.h's "No display
    selected" or Display.cpp's "Unknown screen type"."""
    template = os.path.join(RIGS_DIR, "_template.h")
    if not os.path.isfile(template):
        return
    listed = set(re.findall(r"^\s*//\s*#define\s+(USE_\w+)", open(template).read(),
                            re.MULTILINE))
    missing = set(displays) - listed
    if missing:
        sys.exit(f"include/rigs/_template.h does not list {sorted(missing)}, which "
                 f"generate_font.py supports. Add it to the panel menu.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"usage: {os.path.basename(sys.argv[0])} <rig>\n"
                 f"Available: {', '.join(available()) or '(none)'}")
    write(sys.argv[1])
