#!/usr/bin/env python3
"""Write include/generated/git_hash.h with the short commit hash.

The hash reaches the firmware through a generated header rather than a -D.
A define is part of every compile command's signature, so a new commit — or a
clean<->dirty flip — would recompile every ESP-IDF component object; a header
changes a file's *content*, so only the sources that read it rebuild. Same
reasoning as rig_config.h.

    gen_git_hash.py             # used by the idf.py path in src/CMakeLists.txt
"""

import os
import subprocess

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(PROJECT_ROOT, "include", "generated", "git_hash.h")


def current():
    """Short commit hash, suffixed `-dirty` when the tree has local changes."""
    try:
        return subprocess.check_output(
            ["git", "describe", "--always", "--dirty"],
            cwd=PROJECT_ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except Exception:
        return "unknown"


def write(value=None):
    """Emit the hash header, defaulting to the working tree's. Leaves the file
    alone when unchanged, so its mtime marks a real hash change and nothing
    downstream rebuilds without cause. Returns the value written."""
    value = value or current()
    text = ("// Auto-generated by scripts/gen_git_hash.py — do not edit\n"
            "#pragma once\n"
            f'#define GIT_HASH "{value}"\n')
    if not (os.path.isfile(OUTPUT) and open(OUTPUT).read() == text):
        os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
        with open(OUTPUT, "w") as f:
            f.write(text)
    return value


if __name__ == "__main__":
    print(write())
