#pragma once

#include <stdint.h>

#ifdef __AVR__
  #include <avr/pgmspace.h>
#elif defined(ESP32) || defined(ESP8266)
  #include <pgmspace.h>
#else
  #ifndef PROGMEM
    #define PROGMEM
  #endif
  #ifndef pgm_read_byte
    #define pgm_read_byte(addr) (*(const uint8_t *)(addr))
  #endif
#endif

// 12x12 trend arrow bitmaps for drawBitmap()
// Format: 1 bit per pixel, MSB first, rows top-to-bottom
// Each row is 2 bytes (12 bits used, 4 bits padding)

// Up arrow (filled triangle pointing up)
//     **
//     **
//    ****
//    ****
//   ******
//   ******
//  ********
//  ********
// **********
// **********
//  ********
//     **
static const uint8_t PROGMEM icon_arrow_up[] = {
  0x06, 0x00,  // .....**. ........
  0x06, 0x00,  // .....**. ........
  0x0F, 0x00,  // ....****  ........
  0x0F, 0x00,  // ....****  ........
  0x1F, 0x80,  // ...****** ........
  0x1F, 0x80,  // ...****** ........
  0x3F, 0xC0,  // ..******** ......
  0x3F, 0xC0,  // ..******** ......
  0x7F, 0xE0,  // .********** ....
  0x7F, 0xE0,  // .********** ....
  0x3F, 0xC0,  // ..******** ......
  0x06, 0x00,  // .....**. ........
};

// Down arrow (filled triangle pointing down)
//     **
//  ********
// **********
// **********
//  ********
//  ********
//   ******
//   ******
//    ****
//    ****
//     **
//     **
static const uint8_t PROGMEM icon_arrow_down[] = {
  0x06, 0x00,  // .....**. ........
  0x3F, 0xC0,  // ..******** ......
  0x7F, 0xE0,  // .********** ....
  0x7F, 0xE0,  // .********** ....
  0x3F, 0xC0,  // ..******** ......
  0x3F, 0xC0,  // ..******** ......
  0x1F, 0x80,  // ...****** ........
  0x1F, 0x80,  // ...****** ........
  0x0F, 0x00,  // ....****  ........
  0x0F, 0x00,  // ....****  ........
  0x06, 0x00,  // .....**. ........
  0x06, 0x00,  // .....**. ........
};

// Flat/stable arrow (horizontal bar with right arrow)
//
//
//        **
//         **
// ************
// ************
// ************
// ************
//         **
//        **
//
//
static const uint8_t PROGMEM icon_arrow_flat[] = {
  0x00, 0x00,  // ........  ........
  0x00, 0x00,  // ........  ........
  0x00, 0x80,  // ........*  .......
  0x00, 0x40,  // .........*  ......
  0xFF, 0xF0,  // ************  ....
  0xFF, 0xF0,  // ************  ....
  0xFF, 0xF0,  // ************  ....
  0xFF, 0xF0,  // ************  ....
  0x00, 0x40,  // .........*  ......
  0x00, 0x80,  // ........*  .......
  0x00, 0x00,  // ........  ........
  0x00, 0x00,  // ........  ........
};

#define ICON_ARROW_W 12
#define ICON_ARROW_H 12
